name: Gestao de Vagas Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        run: mvn clean install

      - name: Login docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build -t mrb0305/gestao_vagas .

      - name: Push Docker image
        run: docker push mrb0305/gestao_vagas

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image docker hub
        run: docker pull mrb0305/gestao_vagas:latest
      - name: Stop and remove existing container
        run: |
          docker stop gestao_vagas || true
          docker rm gestao_vagas || true
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name gestao_vagas mrb0305/gestao_vagas:latest -e DATABASE_URL=${{ secrets.DATABASE_URL }} -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}